// <auto-generated />
using System;
using Binary_Project_Structure_DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Binary_Project_Structure_DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180714194837_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AircraftName")
                        .IsRequired();

                    b.Property<DateTime>("DateRelease");

                    b.Property<TimeSpan>("Lifetime");

                    b.Property<int>("TypeAircraftId")
                        .HasMaxLength(3);

                    b.HasKey("Id");

                    b.HasIndex("TypeAircraftId");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Crew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PilotId")
                        .HasMaxLength(3);

                    b.HasKey("Id");

                    b.HasIndex("PilotId");

                    b.ToTable("Crew");
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Departure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AircraftId")
                        .HasMaxLength(3);

                    b.Property<int>("CrewId")
                        .HasMaxLength(3);

                    b.Property<DateTime>("DepartureTime");

                    b.Property<int>("FlightId")
                        .HasMaxLength(3);

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("CrewId");

                    b.HasIndex("FlightId");

                    b.ToTable("Departure");
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrivalPoint")
                        .IsRequired();

                    b.Property<TimeSpan>("ArrivalTime");

                    b.Property<string>("DeparturePoint")
                        .IsRequired();

                    b.Property<TimeSpan>("DepartureTime");

                    b.HasKey("Id");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateBirth");

                    b.Property<int>("Experience");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Pilot");
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Stewardess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CrewId");

                    b.Property<DateTime>("DateBirth");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.ToTable("Stewardess");
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FlightId")
                        .HasMaxLength(3);

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.TypeAircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AircraftModel");

                    b.Property<int>("CarryingCapacity");

                    b.Property<int>("NumberPlaces");

                    b.HasKey("Id");

                    b.ToTable("TypeAircraft");
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Aircraft", b =>
                {
                    b.HasOne("Binary_Project_Structure_DataAccess.Models.TypeAircraft", "TypeAircraft")
                        .WithMany()
                        .HasForeignKey("TypeAircraftId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Crew", b =>
                {
                    b.HasOne("Binary_Project_Structure_DataAccess.Models.Pilot", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Departure", b =>
                {
                    b.HasOne("Binary_Project_Structure_DataAccess.Models.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Binary_Project_Structure_DataAccess.Models.Crew", "Crew")
                        .WithMany()
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Binary_Project_Structure_DataAccess.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Stewardess", b =>
                {
                    b.HasOne("Binary_Project_Structure_DataAccess.Models.Crew")
                        .WithMany("Stewardesses")
                        .HasForeignKey("CrewId");
                });

            modelBuilder.Entity("Binary_Project_Structure_DataAccess.Models.Ticket", b =>
                {
                    b.HasOne("Binary_Project_Structure_DataAccess.Models.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
